# Filename: docker-compose.dev.yml
version: '3.8'
services:
  zzv-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"  # Development port
    volumes:
      - .:/app
      - ./priv/cert:/app/priv/cert
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=mongodb://root:password@mongodb:27017/zzv_dev
      - KAFKA_BROKER=kafka:9092
      - PORT=4000
      - DOMAIN=localhost
      - SECRET_KEY_BASE=d3v3l0pm3ntk3yb@s3f0rzzv10
    depends_on:
      - mongodb
      - kafka

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LOG_RETENTION_HOURS=12

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  mongodb_data:
  ollama_data:
