apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 144.91.76.244/32  # Replace with your VPS Public IP
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertise-public-ip
  namespace: metallb-system
