apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-demo.yaml
  - kafka-demo-statefulset.yaml
  - mongodb-demo-statefulset.yaml
  - spring-boot-demo-deployment.yaml

patches:
  - target:
      kind: Deployment
      name: spring-boot-demo
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value: "myrepo/spring-kafka-streams:latest"
